# Generated by Django 4.2 on 2024-11-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
