# Generated by Django 4.2 on 2024-11-17 21:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('NG', 'Nigeria'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('IN', 'India'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('JP', 'Japan'), ('CN', 'China'), ('BR', 'Brazil'), ('ZA', 'South Africa'), ('IT', 'Italy'), ('ES', 'Spain'), ('RU', 'Russia'), ('MX', 'Mexico'), ('KR', 'South Korea'), ('AR', 'Argentina'), ('NG', 'Nigeria')], default='US', max_length=3, null=True)),
                ('image', models.ImageField(upload_to='company_image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('entertainment', 'Entertainment'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('automotive', 'Automotive'), ('transportation', 'Transportation'), ('real-estate', 'Real Estate'), ('energy', 'Energy'), ('hospitality', 'Hospitality'), ('agriculture', 'Agriculture'), ('media', 'Media'), ('telecommunications', 'Telecommunications'), ('e-commerce', 'E-commerce'), ('food-beverage', 'Food & Beverage'), ('tourism', 'Tourism'), ('logistics', 'Logistics')], max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('can_recruit', models.BooleanField(default=False)),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
