# Generated by Django 4.2 on 2024-11-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_salary_job_salary_min_job_salary_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20),
        ),
    ]
