# Generated by Django 4.2 on 2024-11-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance')], default='FULL_TIME', max_length=20),
        ),
    ]
